name: Release

on:
  create:
     tags:        
       - v*
jobs:
  tests:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os-environment: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - name: Build documentation
      shell: bash
      run: |
        echo "lol r"
