name: Release

on:
  create:
    tags:
      - v*
jobs:
  check_is_valid_target:
    if: github.ref_type == 'tag'
    strategy:
      fail-fast: true
      matrix:
        os-environment: [ubuntu-20.04]
    runs-on: ${{ matrix.os-environment }}
    steps:
      - name: Checker
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "main" the branch that triggered the push event.

      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on default: main".

      - name: Running on the default branch (i.e non tag based branch).
        if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on branch: main".

      - name: Get Ref brach name
        run: |
          echo "${{ steps.branch-name.outputs.ref_branch }}"
        #  Outputs: "main"

      - name: Default branch name
        run: |
          echo "${{ steps.branch-name.outputs.default_branch }}"
        # Outputs: "main" the default branch.
  rel:
    needs: check_is_valid_target
    if: github.ref_type == 'tag'
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os-environment: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - name: Build documentation
      shell: bash
      run: |
        echo "lol r"
