name: Release

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [ main ]    
    tags:        
      - v*
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os-environment: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - name: Build documentation
      shell: bash
      run: |
        echo "lol r"
