name: Release

on:
  create:
    tags:
      - v*
jobs:
  check_is_valid_target:
    if: github.ref_type == 'tag'
    strategy:
      fail-fast: true
      matrix:
        os-environment: [ubuntu-20.04]
    runs-on: ${{ matrix.os-environment }}
    steps:
      - name: Checker
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
  rel:
    needs: check_is_valid_target
    if: github.ref_type == 'tag'
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os-environment: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os-environment }}
    steps:
    - name: Build documentation
      shell: bash
      run: |
        echo "lol r"
